### ISSUE TITLE
feder for text documents

### ISSUE THREAD

**Issue by safakkbilici** [zilliztech/feder#48]
I want to visualize my text documents and so i did. However i didn't find any way to get docids in a specific cluster. For example, when I search over a random vector with feder, library gives me a bunch of clusters. Is it possible to obtain which vectors are stored in a specified cluster?

Actually what i exactly wanted and asked is that, in your example you are able to see images with fine search (distance) (first attached file). I want to show small texts instead of images (second attached file).
![1](https://user-images.githubusercontent.com/44443472/187163723-cd737f2a-5e63-4eb0-bdd8-a222bf2207d0.png)
![2](https://user-images.githubusercontent.com/44443472/187163749-3139dd16-9e10-4f1b-9f5d-661eac14f9cd.png)

**Comment by alwayslove2013** [comment]
Currently, we only support displaying images.  We will release a new version in this week, which supports showing text, or other user-customized information panels.

```
const feder = new Feder({
  source: 'faiss',
  filePath: ivfflatIndexFilePath,
  viewParams: {
    mediaType: 'img',
    mediaCallback: () => null,
  },
});
```
Set `mediaCallback` to `() => null`, and hover the node you are interested in, Feder will show the rowID and the clusterID.
![image](https://user-images.githubusercontent.com/22510720/187178713-df5c926e-82d5-4e9c-bf9f-896730ad1bfd.png)

If you want to know which vectors are in a specific cluster, you can try it.
```
// get the rowIds of vectors that belong to cluster-123.
feder.core.indexMeta.listIds[123] // "list" means "cluster"
```

**Comment by safakkbilici** [comment]
thanks for the quick reply, i'm looking forward to the new release! is there any pythonic version of python```feder.core.indexMeta.listIds[123]``` code snippet. I think this is for JS.

**Comment by alwayslove2013** [comment]
This is the internal data of federjs.`federpy` only supports generating visualizations and cannot access it directly.
Maybe you can try to use faiss to get it.
