### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by safakkbilici** [zilliztech/feder#52]
Is there any updates on new version for feder? You have mentioned about that on my last issue which was about supporting text documents.

**Comment by alwayslove2013** [comment]
I'm sorry to have kept you waiting.

Welcome to try our new version of `Feder`.

About the text display support. We have prepared a demo for you.

https://colab.research.google.com/drive/12L_oJPR-yFDlORpPondsqGNTPVsSsUwi#scrollTo=w8UJB4-K6bUV

You don't need to update the version of `federpy`, it will always be up to date with the latest version of `federjs`. You only need to clear your browser cache when you use it in jupyter-notebook. We will update the documentation to include more usage of the new version of feeder.

Feel free to give us your comments!
