### ISSUE TITLE
How to generate .index file ?

### ISSUE THREAD

**Issue by luancaarvalho** [zilliztech/feder#73]
Hello feder team !

I'm trying to use the project, but I don't know how to generate the .index file, can you help me on this, please ?

**Comment by alwayslove2013** [comment]
`Feder` supports the `index` file generated by `faiss(ivf_flat)` or `hnswlib(hnsw)`.

faiss: https://github.com/facebookresearch/faiss
hnswlib: https://github.com/nmslib/hnswlib

We have also prepared some data examples. I hope this helps you~
https://github.com/zilliztech/feder/tree/main/test/data
